#!/bin/bash
user="$1"
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>✅ NOTIFICATIONS ✅</b>
<code>────────────────────</code>
<b>Protocol:</b> <code>SSH</code>
<b>User:</b> <code>${user}</code>
<b>Status:</b> <code>Telah bebas dari penguncian</code>
<code>────────────────────</code>
<b>🤖 Lain Kali Jangan Multi Login Ya Kak.</b>
<code>────────────────────</code>
"
curl -s --max-time 10 -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" "$URL" >/dev/null
