#!/bin/bash
clear
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
Putih="\033[97m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
BIBlack='\033[1;90m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
GREENBO='\033[1;32m'
bgwhite='\e[40;97;1m'
bgred='\e[41;97;1m'
bggreen='\e[42;97;1m'
bgyellow='\e[43;97;1m'
bgmagenta='\e[45;97;1m'
bgblue='\e[46;97;1m'
bgblack='\e[47;30;1m'
w='\033[97m'
ORANGE='\033[0;34m'
clear
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${BIYellow}BANDWITH MONITOR${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${IGreen}[${BIWhite}01${IGreen}] ${NC}${BIWhite}View Total Remaining Bandwidth${NC}"
echo -e "${IGreen}[${BIWhite}02${IGreen}] ${NC}${BIWhite}View Usage Table Every 5 Minutes${NC}"
echo -e "${IGreen}[${BIWhite}03${IGreen}] ${NC}${BIWhite}View Usage Table Every Hour${NC}"
echo -e "${IGreen}[${BIWhite}04${IGreen}] ${NC}${BIWhite}View Usage Table Every Day${NC}"
echo -e "${IGreen}[${BIWhite}05${IGreen}] ${NC}${BIWhite}View Usage Table Every Month${NC}"
echo -e "${IGreen}[${BIWhite}06${IGreen}] ${NC}${BIWhite}View Usage Table Every Year${NC}"
echo -e "${IGreen}[${BIWhite}07${IGreen}] ${NC}${BIWhite}View Highest Usage Table${NC}"
echo -e "${IGreen}[${BIWhite}08${IGreen}] ${NC}${BIWhite}Hourly Usage Statistics${NC}"
echo -e "${IGreen}[${BIWhite}09${IGreen}] ${NC}${BIWhite}View Current Active Usage${NC}"
echo -e "${IGreen}[${BIWhite}10${IGreen}] ${NC}${BIWhite}View Current Active Traffic Usage${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${BIYellow}Input x or [ Ctrl+C ] • To-${BIWhite}bw${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo ""
read -p "Select menu :" opt
echo -e ""
case $opt in
1)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH REMAINING${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

2)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH EVERY 5 MINUTES${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -5

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

3)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH EVERY HOUR${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -h

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

4)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH EVERY DAY${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -d

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

5)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH EVERY MONTH${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -m

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

6)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}TOTAL SERVER BANDWITH EVERY YEAR${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -y

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

7)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}HIGHEST TOTAL BANDWITH${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -t

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

8)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}HOURLY USED STATISTICS${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -hg

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

9)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}CURRENT LIVE BANDWITH${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e   " Press [ Ctrl+C ]  To-bw"
echo -e ""

vnstat -l

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

10)
clear 
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e "${BIYellow}LIVE TRAFFIC USING BANDWITH${NC}"
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""

vnstat -tr

echo -e ""
echo -e "${BIWhite}─────────────────────────────────────────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

0)
sleep 1
menu
;;
x)
menu
;;
*)
echo -e ""
echo -e "Anda salah tekan"
sleep 1
bw
;;
0) clear ; menu ; menu ;;
x) clear ; menu ;;
*) echo "anda salah tekan" ; sleep 1 ; bw ;;
esac