#!/bin/bash
clear
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RESET='\033[0m'

# Ambil daftar pengguna
users=$(grep -E "^### " "/etc/xray/config.json" | sed -E 's/^### ([^ ]+).*/\1/' | awk '!seen[$0]++')

# Tampilkan daftar pengguna
echo -e "${CYAN}---------------------------------------------${RESET}"
echo -e "${YELLOW}List of Users:${RESET}"
i=1
for user in $users; do
    echo -e "${GREEN}$i) $user${RESET}"
    ((i++))
done
echo -e "${CYAN}---------------------------------------------${RESET}"

# Pilih pengguna
read -p "Select a user by number: " number
selected_user=$(echo "$users" | sed -n "${number}p")
if [ -z "$selected_user" ]; then
    echo -e "${RED}Invalid selection. Exiting.${RESET}"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vmess
fi

# Cek atau buat file batas IP
limit_file="/etc/limit/vmess/ip/${selected_user}"
limit_dir=$(dirname "$limit_file")
if [ ! -d "$limit_dir" ]; then
    mkdir -p "$limit_dir"
    echo -e "${BLUE}Directory $limit_dir created.${RESET}"
fi

if [ -e "$limit_file" ]; then
    current_iplimit=$(cat "$limit_file")
    echo -e "${CYAN}Current IP limit for user ${YELLOW}$selected_user${CYAN}: ${GREEN}$current_iplimit${RESET}"
else
    echo -e "${RED}No IP limit file found for user ${YELLOW}$selected_user${RED}. Creating a new one.${RESET}"
    current_iplimit="0"
fi

# Masukkan batas IP baru
read -p "Input new IP limit: " new_iplimit
if [ -z "$new_iplimit" ]; then
    echo -e "${RED}Invalid input. Exiting.${RESET}"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vmess
else
    echo "$new_iplimit" > "$limit_file"
    echo -e "${GREEN}IP limit updated successfully for user ${YELLOW}$selected_user${GREEN}.${RESET}"
    echo -e "${CYAN}New IP limit: ${GREEN}$new_iplimit${RESET}"
fi

read -n 1 -s -r -p "Press any key to back on menu"
m-vmess