#!/bin/bash
clear
# Definisi warna
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
Putih="\033[97m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
BIBlack='\033[1;90m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
GREENBO='\033[1;32m'
bgwhite='\033[40;97;1m'
bgred='\033[41;97;1m'
bggreen='\033[42;97;1m'
bgyellow='\033[43;97;1m'
bgmagenta='\033[45;97;1m'
bgblue='\033[46;97;1m'
bgblack='\033[47;30;1m'
w='\033[97m'
ORANGE='\033[0;34m'

clear
BOT_DB="/etc/bot/.bot.db"

if [[ ! -f "$BOT_DB" || $(grep -c -E "^#bot# " "$BOT_DB" 2>/dev/null) -eq 0 ]]; then
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo -e "${BIYellow}DELETE BOT NOTIFICATION${NC}"
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    echo ""
    echo -e "You have no existing clients!"
    echo ""
    echo -e "${BIWhite}──────────────────────────────────────${NC}"
    read -n 1 -s -r -p "Press [ Enter ] to return to the menu"
    m-bot-notif
fi

clear

# Ambil token bot dan ID Telegram dari database
CHATID=$(awk '/^#bot# / {print $3; exit}' "$BOT_DB" 2>/dev/null)
KEY=$(awk '/^#bot# / {print $2; exit}' "$BOT_DB" 2>/dev/null)

# Hapus hanya baris yang sesuai dari database
sed -i "/^#bot# $KEY $CHATID/d" "$BOT_DB"

clear
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e "${IGreen}SUCCESSFULLY DELETED BOT NOTIFICATION${NC}"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo -e " Bot Token    : $KEY"
echo -e " ID Telegram  : $CHATID"
echo -e "${BIWhite}──────────────────────────────────────${NC}"
echo ""
read -n 1 -s -r -p "Press [ Enter ] to return to the menu"
m-bot-notif
