#!/bin/bash
clear
PERMISSION() {
    MYIP=$(curl -sS ipv4.icanhazip.com)

    TODAY_DATE=$(date +'%Y-%m-%d')

    AUTHORIZED_ENTRY=$(curl -sS https://raw.githubusercontent.com/sweaterpinktools/os/main/ip | grep -w "$MYIP" | head -1)

    if [[ -n "$AUTHORIZED_ENTRY" ]]; then
        # IP_FROM_ENTRY sekarang adalah field ke-4
        IP_FROM_ENTRY=$(echo "$AUTHORIZED_ENTRY" | awk '{print $4}')
        # EXP_DATE_OR_LIFETIME_STATUS sekarang adalah field ke-3
        EXP_DATE_OR_LIFETIME_STATUS=$(echo "$AUTHORIZED_ENTRY" | awk '{print $3}') 

        if [ "$MYIP" = "$IP_FROM_ENTRY" ]; then
            # Cek apakah statusnya 'lifetime'
            if [[ "$EXP_DATE_OR_LIFETIME_STATUS" == "lifetime" ]]; then
                echo -e "\033[1;92mPermission Accepted (Lifetime User)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Pengguna Lifetime)${NC}"
            # Jika bukan 'lifetime', baru lakukan perbandingan tanggal
            elif [[ "$TODAY_DATE" < "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;92mPermission Accepted\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan${NC}"
            elif [[ "$TODAY_DATE" == "$EXP_DATE_OR_LIFETIME_STATUS" ]]; then
                echo -e "\033[1;93mPermission Accepted (Today is Expiry Date)\033[0m"
                echo -e "\033[1;97mAkses Di Izinkan (Hari Ini Kadaluarsa)${NC}"
            else
                echo -e "\033[1;91mPermission Denied (Expired)\033[0m"
                echo -e "\033[1;97mAkses Di Tolak (Kadaluarsa)${NC}"
                read -n 1 -s -r -p "Press [ Enter ] to Exit"
                exit 1
            fi
        else
            echo -e "\033[1;91mPermission Denied (IP Mismatch)\033[0m"
            echo -e "\033[1;97mAkses Di Tolak (IP Tidak Cocok)${NC}"
            read -n 1 -s -r -p "Press [ Enter ] to Exit"
            exit 1
        fi
    else
        echo -e "\033[1;91mPermission Denied (IP Not Found)\033[0m"
        echo -e "\033[1;97mAkses Di Tolak (IP Tidak Ditemukan)${NC}"
        read -n 1 -s -r -p "Press [ Enter ] to Exit"
        exit 1
    fi
}

PERMISSION
clear
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
Putih="\033[97m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
BIBlack='\033[1;90m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
GREENBO='\033[1;32m'
bgwhite='\e[40;97;1m'
bgred='\e[41;97;1m'
bggreen='\e[42;97;1m'
bgyellow='\e[43;97;1m'
bgmagenta='\e[45;97;1m'
bgblue='\e[46;97;1m'
bgblack='\e[47;30;1m'
w='\033[97m'
ORANGE='\033[0;34m'
clear
echo -e "${BIGreen}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${BIGreen}  $NC$COLBG1               ${BICyan}• VPS SETTING •                 ${BIGreen}  $NC"
echo -e "${BIGreen}└─────────────────────────────────────────────────┘${NC}"
echo -e " ${BIGreen}┌─────────────────────────────────────────────────┐${NC}"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}01${BICyan}]${NC} ${BIGreen}• ${BICyan}Ganti UUID Xray   ${BICyan}[${BIGreen}08${BICyan}]${NC} ${BIGreen}• ${BICyan}Info Port"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}02${BICyan}]${NC} ${BIGreen}• ${BICyan}Install UDP       ${BICyan}[${BIGreen}09${BICyan}]${NC} ${BIGreen}• ${BICyan}Rebuild VPS"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}03${BICyan}]${NC} ${BIGreen}• ${BICyan}setupreboot       ${BICyan}[${BIGreen}10${BICyan}]${NC} ${BIGreen}• ${BICyan}Trial Xray"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}04${BICyan}]${NC} ${BIGreen}• ${BICyan}Autoreboot        ${BICyan}[${BIGreen}11${BICyan}]${NC} ${BIGreen}• ${BICyan}fix-nginx"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}05${BICyan}]${NC} ${BIGreen}• ${BICyan}speedtest         ${BICyan}[${BIGreen}12${BICyan}]${NC} ${BIGreen}• ${BICyan}BANDWITH"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}06${BICyan}]${NC} ${BIGreen}• ${BICyan}Service Mulog IP  ${BICyan}[${BIGreen}13${BICyan}]${NC} ${BIGreen}• ${BICyan}Change DROPBEAR"
echo -e " ${BIGreen} $NC${BICyan}[${BIGreen}07${BICyan}]${NC} ${BIGreen}• ${BICyan}Check Ram & CPU   ${BICyan}[${BIGreen}14${BICyan}]${NC} ${BIGreen}• ${BICyan}Change Domain"
echo -e " ${BIGreen}└─────────────────────────────────────────────────┘${NC}"
echo -e " ${BIGreen}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${BIYellow}Input x or [ Ctrl+C ] • To-${BIWhite}Exit${NC}"
echo -e " ${BIGreen}└─────────────────────────────────────────────────┘${NC}"
echo ""
read -p "Select menu :" opt
echo -e ""
case $opt in
1) clear ; ganti-id ;;
2) clear ; install-udp ; read -p "Press enter Back To Menu" ; m-setting ;;
3) clear ; setupreboot ;;
4) clear ; autoreboot ;;
5) clear ; speedtest ;;
6) clear ; m-mulog ;;
7) clear ; htop ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; m-setting ;;
8) clear ; prot ;;
9) clear ; m-rebuild ;;
10) clear ; m-trial ;;
11) clear ; fix-nginx ;;
12) clear ; bw ;;
13) clear ; m-dropbear ; read -n 1 -s -r -p "Press [ Enter ] to back on menu" ; menu ;;
14) clear ; m-domain ;;
0) clear ; menu ; exit ;;
x) menu ;;
*) echo "anda salah tekan" ; sleep 1 ; m-setting ;;
esac
