#!/bin/bash
clear
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
Putih="\033[97m"
RED='\033[0;31m'
NC='\033[0m'
green='\033[0;32m'
BIBlack='\033[1;90m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
GREENBO='\033[1;32m'
bgwhite='\e[40;97;1m'
bgred='\e[41;97;1m'
bggreen='\e[42;97;1m'
bgyellow='\e[43;97;1m'
bgmagenta='\e[45;97;1m'
bgblue='\e[46;97;1m'
bgblack='\e[47;30;1m'
w='\033[97m'
ORANGE='\033[0;34m'
clear
restart_all_services() {
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Fail2ban${NC}"
systemctl restart fail2ban 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Cron${NC}"
systemctl restart cron 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Nginx${NC}"
systemctl restart nginx 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Xray${NC}"
systemctl restart xray 2>/dev/null
systemctl restart private 2>/dev/null
systemctl restart public 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Haproxy${NC}"
systemctl restart haproxy 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting SlowDNS${NC}"
systemctl restart server-sldns 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting UDP Custom${NC}"
systemctl restart udp-custom 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}Restarting Noobzvpns${NC}"
systemctl restart noobzvpns 2>/dev/null
sleep 0.5
echo -e "${IGreen}[${BIWhite}INFO${IGreen}]${NC} ${BIYellow}ALL Service Restarted${NC}"
echo ""
read -n 1 -s -r -p "Press any key to back on system menu"
menu
}

restart_all_services
