#!/bin/bash
clear
greenBe="\033[5;32m"
# Fungsi untuk mencetak teks berwarna merah
red() { 
    echo -e "\\033[91;1m${*}\\033[0m"
}

clear

# Fungsi untuk menampilkan loading bar
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 15; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

# Fungsi untuk merestart service bot
res1() {
    systemctl restart private
}

# Menjalankan netfilter-persistent
netfilter-persistent

clear


fun_bar 'res1'

echo -e "\e[5;32mSuccessfully Restart Bot Private\e[0m"
sleep 1
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
m-private