#!/bin/bash
clear
BC='\e[38;5;195m'
R1='\e[38;5;155m'
Suffix='\e[0m'

# Header
echo -e "${BC}---------------------------------------------${Suffix}"
echo -e "${R1}DETAILS ACCOUNT VLESS${Suffix}"
echo -e "${BC}---------------------------------------------${Suffix}"

# Mengambil daftar akun dan tanggal kedaluwarsa dari konfigurasi Xray
accounts=$(grep -E "^#& " "/etc/xray/config.json" | awk '{print $2, $3}' | sort -u)

# Menampilkan daftar akun dan tanggal kedaluwarsa
i=1 # Variabel penghitung untuk nomor urut
declare -a account_array
while read AKUN exp; do
    # Cek apakah informasi username dan tanggal kedaluwarsa valid
    if [[ -n "$AKUN" && -n "$exp" && "$AKUN" != " " && "$exp" != " " ]]; then
        # Menampilkan informasi user dengan nomor urut tanpa status locked/unlocked
        printf "%-3s %-17s %-17s\n" "$i)" "$AKUN" "$exp"
        account_array+=("$AKUN")  # Menyimpan akun dalam array untuk pemilihan selanjutnya
        ((i++))  # Increment angka untuk user berikutnya
    fi
done <<< "$accounts"

# Meminta input nomor pengguna
echo ""
read -p "Just input Number: " number

# Validasi input hanya angka
if ! [[ "$number" =~ ^[0-9]+$ ]]; then
    echo -e "\e[31mInvalid input. Please enter a number.\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vless
fi

# Memilih user berdasarkan nomor yang dimasukkan
selected_user="${account_array[$((number - 1))]}"  # Mengambil user berdasarkan input nomor

# Periksa apakah username valid
if [ -z "$selected_user" ]; then
    echo -e "\e[31mNumber is missing or incorrect.\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vless
fi

# Tampilkan Detail Akun User
detail_file="/detail/vless/$selected_user.txt"
if [[ -f "$detail_file" ]]; then
    clear
    echo -e "${BC}---------------------------------------------${Suffix}"
    echo -e "${R1}DETAILS FOR USER: $selected_user${Suffix}"
    echo -e "${BC}---------------------------------------------${Suffix}"
    cat "$detail_file"
    echo -e "${BC}---------------------------------------------${Suffix}"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vless
else
    echo -e "\e[31mDetail file not found for user: $selected_user\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-vless
fi