#!/bin/bash
clear
BC='\e[38;5;195m'
R1='\e[38;5;155m'
Suffix='\e[0m'

# Header
echo -e "${BC}-----------------------------------------${Suffix}"
echo -e "${R1}DETAILS ACCOUNT SSH${Suffix}"
echo -e "${BC}-----------------------------------------${Suffix}"

# Variabel untuk menyimpan daftar user
users=""
i=1 # Variabel penghitung untuk nomor urut

# Membaca user dari /etc/passwd
while read expired; do
    AKUN="$(echo $expired | cut -d: -f1)"
    ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
    exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
    status="$(passwd -S $AKUN | awk '{print $2}')"
    if [[ $ID -ge 1000 ]]; then
        users+="$AKUN "
        # Menampilkan informasi user dengan nomor urut
        if [[ "$status" = "L" ]]; then
            printf "%-3s %-17s %2s %-17s %2s \n" "$i)" "$AKUN" "$exp"
        else
            printf "%-3s %-17s %2s %-17s %2s \n" "$i)" "$AKUN" "$exp"
        fi
        ((i++)) # Increment angka untuk user berikutnya
    fi
done < /etc/passwd

# Periksa apakah ada user yang ditemukan
if [[ -z "$users" ]]; then
    echo -e "\e[31mNo users found in the configuration file.\e[0m"
    echo -e "${BC}-----------------------------------------${Suffix}"
    exit 1
fi

echo -e "${BC}-----------------------------------------${Suffix}"

# Minta pengguna memilih nomor
echo ""
read -p "Just input Number: " number

# Validasi input hanya angka
if ! [[ "$number" =~ ^[0-9]+$ ]]; then
    echo -e "\e[31mInvalid input. Please enter a number.\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-ssh
fi

# Dapatkan username berdasarkan nomor yang dipilih
selected_user=$(echo $users | awk -v n="$number" '{print $n}')

# Periksa apakah username valid
if [ -z "$selected_user" ]; then
    echo -e "\e[31mNumber is missing or incorrect.\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-ssh
fi

# Tampilkan Detail Akun User
detail_file="/detail/ssh/$selected_user.txt"
if [[ -f "$detail_file" ]]; then
    clear
    echo -e "${BC}-----------------------------------------${Suffix}"
    echo -e "${R1}DETAILS FOR USER: $selected_user${Suffix}"
    echo -e "${BC}-----------------------------------------${Suffix}"
    cat "$detail_file"
    echo -e "${BC}-----------------------------------------${Suffix}"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-ssh
else
    echo -e "\e[31mDetail file not found for user: $selected_user\e[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    m-ssh
fi